FORMAT: 1A
HOST: https://app.eaternity.org/gastro/

# Eaternity Gastro Backend

Things to clarify:

- format of calculated values (how many digits)
- error message handling (e.g. InvalidConfigurationException)
- component type (commercial, conceptual product etc)

- menu-line-id: we need to fill that for existing recipes from the server manually.
And we can assume that three menu lines exist with ids 1,2 and 3

## Menu Collection [/menus]

### List All Menus [GET]

Query Parameters: kitchen-id

+ Response 200 (application/json)

        {
            "results":[
                {
                    "id": "M12312”,
                    "title": "Arabic Risotto with Salad”,
                    "servings": 40,
                    "co2Value": 35,
                    "co2Rating": "e",
                    "vitaScore": 822
                    "vitaScoreRating": "b",
                    "waterScarcity": 22,
                    "waterScarcityRating": "c",
                    "nutritionalBalanced": true,
                    "nutrients": [
                        {
                            "nutrient": "ENERC",
                            "quantity": { "amount":243, "unit": "kcal" },
                        },
                        {
                            "nutrient": "FAT",
                            "quantity": { "amount":22, "unit": "g" },
                        },
                        ...
                    ],
                    "menuLineId": 232,
                    "instructions": "some very long text with \n etc."
                    "components":[
                        {
                            "section": "salad",
                            "quantity": { "amount":100, "unit": "g" },
                            "origin": "local",
                            "transport": "ground",
                            "production": "organic",
                            "conservation": "fresh",
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "recipe"
                                }
                        },
                        {
                            "section": "main course",
                            "quantity": { "amount":2, "unit": "servings" },
                            "origin": "",
                            "transport": "air",
                            "production": "standard",
                            "conservation": "dried",
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "recipe"
                                }
                        },
                        ...
                    ]
                },
                ...
            ]
        }

        
### Create new Menu [POST]

+ Request (application/json)

        {
            "title": "Arabic Risotto with Salad”,
            "servings": 40,
            "menuLineId": 232,
            "instructions": "some very long text with \n etc."
            "components":[
                {
                    "section": "salad",
                    "quantity": { "amount":100, "unit": "g" },
                    "origin": "local",
                    "transport": "ground",
                    "production": "organic",
                    "conservation": "fresh",
                    "component":
                        {
                            "id": "X20Y",
                            "type": "recipe"
                        }
                },
                {
                    "section": "main course",
                    "quantity": { "amount":2, "unit": "servings" },
                    "origin": "",
                    "transport": "air",
                    "production": "standard",
                    "conservation": "dried",
                    "component":
                        {
                            "id": "X20Y",
                            "type": "recipe"
                        }
                },
                ...
            ]
        }

+ Response 200 (application/json)

## Menu [/menus/{id}]

### Create/update existing Menu [PUT]

+ Request (application/json)

        {
            "title": "Arabic Risotto with Salad”,
            "servings": 40,
            "menuLineId": 232,
            "instructions": "some very long text with \n etc."
            "components":[
                {
                    "section": "salad",
                    "quantity": { "amount":100, "unit": "g" },
                    "origin": "local",
                    "transport": "ground",
                    "production": "organic",
                    "conservation": "fresh",
                    "component":
                        {
                            "id": "X20Y",
                            "type": "recipe"
                        }
                },
                {
                    "section": "main course",
                    "quantity": { "amount":2, "unit": "servings" },
                    "origin": "",
                    "transport": "air",
                    "production": "standard",
                    "conservation": "dried",
                    "component":
                        {
                            "id": "X20Y",
                            "type": "recipe"
                        }
                },
                ...
            ]
        }

+ Response 200 (application/json)

### Delete Menu [DELETE]

+ Response 200 (application/json)


## Recipe Collection [/recipes]

### List All Recipes [GET]

+ Response 200 (application/json)

        {
            "results":[
                {
                    "id": "M12312”,
                    "title": "Arabic Risotto with Salad”,
                    "servings": 40,
                    "co2Value": 35,
                    "co2Rating": "e",
                    "vitaScore": 822
                    "vitaScoreRating": "b",
                    "waterScarcity": 22,
                    "waterScarcityRating": "c",
                    "nutritionalBalanced": true,
                    "nutrients": [
                        {
                            "nutrient": "ENERC",
                            "quantity": { "amount":243, "unit": "kcal" },
                        },
                        {
                            "nutrient": "FAT",
                            "quantity": { "amount":22, "unit": "g" },
                        },
                        ...
                    ],
                    "instructions": "some very long text with \n etc."
                    "components":[
                        {
                            "quantity": { "amount":100, "unit": "g" },
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "recipe"
                                }
                        },
                        {
                            "quantity": { "amount":2, "unit": "servings" },
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "product"
                                }
                        },
                        ...
                    ]
                },
                ...
            ]
        }

      
## Recipe [/recipes/{id}]  

### Get One Recipe [GET]

+ Response 200 (application/json)

        {
            "results":[
                {
                    "id": "M12312”,
                    "title": "Arabic Risotto with Salad”,
                    "servings":40,
                    "co2Value":35,
                    "co2Rating": "e",
                    "vitaScore":822
                    "vitaScoreRating": "b",
                    "waterScarcity": 22,
                    "waterScarcityRating": "c",
                    "nutritionalBalanced": true,
                    "nutrients": [
                        {
                            "nutrient": "ENERC",
                            "quantity": { "amount":243, "unit": "kcal" },
                        },
                        {
                            "nutrient": "FAT",
                            "quantity": { "amount":22, "unit": "g" },
                        },
                        ...
                    ],
                    "instructions": "some very long text with \n etc."
                    "components":[
                        {
                            "quantity": { "amount":100, "unit": "g" },
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "recipe"
                                }
                        },
                        {
                            "quantity": { "amount":150, "unit": "g" },
                            "component":
                                {
                                    "id": "X20Y",
                                    "type": "recipe"
                                }
                        },
                        ...
                    ]
                }
            ]
        }


### Create a New Recipe [PUT]


+ Request (application/json)

        { 
            "title": "Arabic Risotto with Salad",
            "servings": 4,
            "instructions": "some very long text with \n etc."
            "components":[
                {
                    "quantity": { "amount":100, "unit": "g" },
                    "component": 
                        { 
                            "id": "X20Y",
                            "type": "recipe",
                        }
                },
                {
                    "quantity": { "amount":150, "unit": "g" },
                    "component": 
                        { 
                            "id": "G563",
                            "type": "product"
                        }
                },
                …
            ]
            }
        }



+ Response 201 (application/json)


## Product Collection [/products] 

### List All Products [GET]

+ Response 200 (application/json)

        {
            "results":[
                {
                    "id": "G563",
                    "name": "Zucchini",
                    "type": "product"
                    "configurationPossibilities": {
                        "production": ["standard", "organic"],
                        "conservation": ["fresh", "dried"]
                    }
                },
                {
                    "id": "G563",
                    "name": "Zucchini",
                    "type": "product"
                    "configurationPossibilities": {
                        "production": ["standard", "suckler-cow"],
                        "conservation": ["fresh", "frozen", "conserved"]
                    }
                },
                ...
            ]
        }
     
     
## Product [/products/{id}]     
        
### Create/update new product [PUT]

+ Request (application/json)

        {
            "id": "G563",
            "name": "Zucchini",
            "type": "product"
        }

+ Response 201 (application/json)